SELECT SUB.AUTHOR_ID, A.AUTHOR_NAME, SUB.CATEGORY, SUM(SUB.SALES * SUB.PRICE) AS TOTAL_SALES
FROM 
(
    SELECT S.BOOK_ID, S.SALES, B.CATEGORY, B.AUTHOR_ID, B.PRICE, S.SALES_DATE
    FROM BOOK_SALES S
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
) AS SUB
JOIN AUTHOR A ON SUB.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(SUB.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY SUB.AUTHOR_ID, A.AUTHOR_NAME, SUB.CATEGORY
ORDER BY SUB.AUTHOR_ID ASC, SUB.CATEGORY DESC;