WITH RECURSIVE ECOLI_GENS AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, EG.GEN + 1 
    FROM ECOLI_DATA ED
    JOIN ECOLI_GENS EG ON ED.PARENT_ID = EG.ID
    
    WHERE EG.GEN < 3
    
)

SELECT ID
FROM ECOLI_GENS
WHERE GEN = 3
ORDER BY ID ASC