SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
LEFT JOIN ITEM_TREE T2 ON I.ITEM_ID = T2.PARENT_ITEM_ID
WHERE T2.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC