SELECT SUB.FOOD_TYPE, SUB.REST_ID, SUB.REST_NAME, SUB.FAVORITES
FROM (
    SELECT *, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
) SUB
WHERE SUB.RNK = 1
ORDER BY SUB.FOOD_TYPE DESC