-- 코드를 입력하세요
SELECT SUB.REST_ID, SUB.REST_NAME, SUB.FOOD_TYPE, SUB.FAVORITES AS FAVORITES, SUB.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) AS SUB
JOIN REST_REVIEW R ON SUB.REST_ID = R.REST_ID
GROUP BY SUB.REST_ID, SUB.REST_NAME, SUB.FOOD_TYPE, SUB.FAVORITES, SUB.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC 