SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE S
JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(S.SALES_DATE, '%Y-%m'), GENDER
ORDER BY YEAR, MONTH, GENDER