


SELECT
    YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / U.CNT, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S JOIN (
    SELECT *, (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) U ON S.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH











