SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT S.USER_ID) / SUB.CNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S 
CROSS JOIN
    (SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021') AS SUB
JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE YEAR(I.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;