WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, EG.GEN + 1
    FROM ECOLI_GEN EG
    JOIN ECOLI_DATA ED ON ED.PARENT_ID = EG.ID
    
)

SELECT COUNT(*) AS COUNT, EG.GEN AS GENERATION
FROM ECOLI_GEN EG
LEFT JOIN ECOLI_DATA ED ON EG.ID = ED.PARENT_ID
WHERE ED.ID IS NULL
GROUP BY EG.GEN
ORDER BY GENERATION ASC