SELECT H.HISTORY_ID, 
TRUNCATE(
CASE 
    WHEN P.PLAN_ID IS NULL THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
    ELSE
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (C.DAILY_FEE - (C.DAILY_FEE * MAX(P.DISCOUNT_RATE)) / 100) 
    END, 0)
        AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= SUBSTRING(P.DURATION_TYPE, 1, INSTR(P.DURATION_TYPE, '일')-1)
WHERE C.CAR_TYPE = '트럭'
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, H.HISTORY_ID DESC