
SELECT SUB.HISTORY_ID, 
    CASE 
        WHEN P.PLAN_ID IS NULL THEN SUB.DAILY_FEE * SUB.DURATION
        ELSE TRUNCATE(SUB.DURATION * (SUB.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)), 0)
    END AS FEE
FROM
(SELECT 
    H.HISTORY_ID, C.CAR_ID, C.DAILY_FEE, C.CAR_TYPE,
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE NULL 
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID) AS SUB
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON SUB.CAR_TYPE = P.CAR_TYPE AND SUB.DURATION_TYPE = P.DURATION_TYPE
WHERE SUB.CAR_TYPE = '트럭'
ORDER BY FEE DESC, SUB.HISTORY_ID DESC