

SELECT H.HISTORY_ID,
    CASE
        WHEN P.PLAN_ID IS NULL THEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE 
        ELSE TRUNCATE((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)), 0) 
    END AS FEE
FROM 
(
SELECT *,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC






