SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) j ON j.FLAVOR = f.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.JULY_TOTAL) DESC
LIMIT 3;