WITH RECURSIVE HOUR_TABLE AS (
    
    SELECT 0 AS HOUR
    
    UNION ALL

    SELECT H.HOUR + 1 AS HOUR
    FROM HOUR_TABLE H
    
    WHERE H.HOUR < 23 
)

SELECT H.HOUR, COUNT(O.ANIMAL_ID) AS COUNT
FROM HOUR_TABLE H LEFT JOIN ANIMAL_OUTS O ON H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR