SELECT U.USER_ID, U.NICKNAME, SUB.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN 
(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) AS SUB
ON U.USER_ID = SUB.WRITER_ID
WHERE SUB.TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC