SELECT H.EMP_NO, H.EMP_NAME,
    CASE
        WHEN SUB.TOTAL_SCORE >= 96 THEN 'S'
        WHEN SUB.TOTAL_SCORE >= 90 THEN 'A'
        WHEN SUB.TOTAL_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SUB.TOTAL_SCORE >= 96 THEN (H.SAL * 0.2)
        WHEN SUB.TOTAL_SCORE >= 90 THEN (H.SAL * 0.15)
        WHEN SUB.TOTAL_SCORE >= 80 THEN (H.SAL * 0.1) 
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES H
JOIN 
    (SELECT EMP_NO, AVG(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO) SUB
ON H.EMP_NO = SUB.EMP_NO
ORDER BY H.EMP_NO;




















