SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM (
    SELECT T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
) AS SUB
JOIN ITEM_INFO I2 ON SUB.ITEM_ID = I2.ITEM_ID
ORDER BY I2.ITEM_ID DESC