SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN (SELECT * FROM SKILLCODES WHERE NAME = 'C#' OR NAME = 'Python') AS S
WHERE D.SKILL_CODE & S.CODE = S.CODE
ORDER BY D.ID ASC;