
SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, (S.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, D.ID
FROM ECOLI_DATA D
JOIN
(
    SELECT DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS DIFFERENTIATION_DATE, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')
) AS S
ON DATE_FORMAT(D.DIFFERENTIATION_DATE, '%Y') = S.DIFFERENTIATION_DATE
ORDER BY YEAR, YEAR_DEV