SELECT COUNT(*) AS FISH_COUNT, MAX(F.LENGTH) AS MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
JOIN
(
    SELECT FISH_TYPE, AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) SUB
ON F.FISH_TYPE = SUB.FISH_TYPE
WHERE SUB.AVG_LENGTH >= 33
GROUP BY F.FISH_TYPE
ORDER BY F.FISH_TYPE 