SET @max_price := 0;
SET @min_price := 0;

SELECT MAX(PRICE), MIN(PRICE) INTO @max_price, @min_price FROM PRODUCT;


WITH RECURSIVE PRICE_TABLE AS (
    SELECT FLOOR(@min_price/10000) * 10000 AS PRICE_GROUP
    
    UNION ALL
    
    SELECT P.PRICE_GROUP + 10000 AS PRICE_GROUP
    FROM PRICE_TABLE P
    
    WHERE P.PRICE_GROUP < FLOOR(@max_price/10000) * 10000
)

SELECT PR.PRICE_GROUP, COUNT(*) AS COUNT
FROM PRICE_TABLE PR JOIN PRODUCT P ON PR.PRICE_GROUP <= P.PRICE AND P.PRICE < PR.PRICE_GROUP + 10000
GROUP BY PR.PRICE_GROUP
ORDER BY PR.PRICE_GROUP
